//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Slovo.Resources
{
   using System;

   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   public class CommonResources
   {

      internal CommonResources()
      {
      }

      /// <summary>
      ///   Looks up a localized string similar to About.
      /// </summary>
      public static string About
      {
         get
         {
            return GetString("About");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Slovo.
      /// </summary>
      public static string ApplicationName
      {
         get
         {
            return GetString("ApplicationName");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Apply.
      /// </summary>
      public static string Apply
      {
         get
         {
            return GetString("Apply");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Back.
      /// </summary>
      public static string Back
      {
         get
         {
            return GetString("Back");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Buy.
      /// </summary>
      public static string Buy
      {
         get
         {
            return GetString("Buy");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You are using trial application version, in which available translations of words beginning with the letter &apos;A&apos; only. To translate all words, please buy the application..
      /// </summary>
      public static string BuyProgramDescription
      {
         get
         {
            return GetString("BuyProgramDescription");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to © Copyright 2014. Version {0}.{1}.
      /// </summary>
      public static string Copyright
      {
         get
         {
            return GetString("Copyright");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Delete.
      /// </summary>
      public static string Delete
      {
         get
         {
            return GetString("Delete");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to History.
      /// </summary>
      public static string History
      {
         get
         {
            return GetString("History");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to The application uses: {0}1. Electronic Mueller dictionary database, distributed under the GNU GPL license &lt;http://mueller-dic.chat.ru/Mueller7_koi.html&gt;{0}2. WordNet® lexical database &lt;http://wordnet.princeton.edu&gt;.
      /// </summary>
      public static string License
      {
         get
         {
            return GetString("License");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Listen.
      /// </summary>
      public static string Listen
      {
         get
         {
            return GetString("Listen");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Next.
      /// </summary>
      public static string Next
      {
         get
         {
            return GetString("Next");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Feedback.
      /// </summary>
      public static string PrivateFeedback
      {
         get
         {
            return GetString("PrivateFeedback");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Search.
      /// </summary>
      public static string Search
      {
         get
         {
            return GetString("Search");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Vocabularies.
      /// </summary>
      public static string Vocabularies
      {
         get
         {
            return GetString("Vocabularies");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to WordNet dictionary - 146000 entries. 
      ///Mueller dictionary - 66000 entries.
      ///Ru-En dictionary - 32000 entries.
      ///Ojegov dictionary - 38000 entries..
      /// </summary>
      public static string VocabulariesCapacity
      {
         get
         {
            return GetString("VocabulariesCapacity");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Offline multilingual dictionary with detailed translation of each word..
      /// </summary>
      public static string VocabularyDescription
      {
         get
         {
            return GetString("VocabularyDescription");
         }
      }

      private static string GetString(string key)
      {
         Windows.ApplicationModel.Resources.ResourceLoader loader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("CommonResources");
         return loader.GetString(key);
      }

   }

}